name: DeepProject
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pillow
  - tqdm
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.5.1
      - torchvision==0.20.1
      - diffusers==0.30.0
      - transformers==4.44.0
      - accelerate
      - safetensors
      - torchmetrics 
      - piq
      - clean-fid
      - torch-fidelity
      - scikit-image
      - image-reward
      - opencv-contrib-python
      - datasets
      - pyiqa
      - brisque